replicaCount: 3

image:
  repository: https://hub.docker.com/r/petyrveliki/petar-custom-nginx
  tag: latest

service:
  name: my-service
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: "manual"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  host: example.com
resources: {}
 