apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: poker-static-assets
  labels:
    app.kubernetes.io/instance: v1
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      namespace: poker-static-assets
    spec:
      containers:
        - image: petyrveliki/petar-custom-nginx
          name: myapp
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: my-pv
      securityContext: {}
      volumes:
        - name: my-pv
          persistentVolumeClaim:
            claimName: pvc-example