apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poker-static-assets-dcpl.fullname" . }}
  namespace: test  # Set namespace here
  labels:
    {{- include "poker-static-assets-dcpl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: {{ include "poker-static-assets-dcpl.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "poker-static-assets-dcpl.name" . }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: nginx-pvc