{{- if .Values.ingress.enabled -}}
{{- $labels := include "nebula.labels" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPort := tpl .Values.ingress.port . -}}
{{- $name := include "nebula.name" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ include "nebula.namespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
    {{- if .Values.ingress.extraLabels }}
      {{- tpl (.Values.ingress.extraLabels | toYaml) $ | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $ingressPort }}
  {{- end }}
{{- end }}