apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-chart.fullname" . }}-pvc
spec:
   accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}