apiVersion: v1
kind: PersistentVolume
metadata:
  name: poker-static-asset-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data