apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poker-static-assets-dcpl.fullname" . }}-pvc
  labels:
    {{- include "poker-static-assets-dcpl.labels" . | nindent 4 }}
spec:
  accessModes:
    ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}