apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2-example
  namespace: poker-static-assets
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi