kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: poker-static-assets
  name: pv-manager
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "delete", "update"]