apiVersion: v1
kind: Service
metadata:
  name: {{ include "poker-static-assets-dcpl.fullname" . }}
  namespace: test  # Set namespace here
  labels:
    {{- include "poker-static-assets-dcpl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "poker-static-assets-dcpl.name" . }}