piVersion: v1
kind: Service
metadata:
  name: poker-static-assets
  namespace: test
  annotations:
    meta.helm.sh/release-name: poker-static-assets-dcpl
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: poker-static-assets-dcpl
---
apiVersion: v1
kind: Service
metadata:
  name: poker-static-assets-dcpl
  namespace: test
  annotations:
    meta.helm.sh/release-name: poker-static-assets-dcpl
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP  # Adjust the type based on your requirements
  ports:
    - port: 80
  selector:
    app: poker-static-assets-dcpl