apiVersion: v1
kind: Service
metadata:
  name: psa-service
spec:
  selector:
    app: poker-static-assets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed